# -*- coding: utf-8 -*-
"""evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXSTkRuv894wGjJr5UG3TYBgdM-Eat70
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, roc_auc_score
from tensorflow.keras.utils import to_categorical

from model_3d import get_model

# 1. Cargar datos de validación (Mismo random_state=42 para consistencia)
print("Cargando set de validación...")
data_y = np.load('data/data_ytrain.npy')
data_x = np.load('data/data_xtrain.npy')
ytrain_categorical = to_categorical(data_y[:, 0], num_classes=2)

_, X_val, _, y_val = train_test_split(
    data_x, ytrain_categorical, test_size=0.2, stratify=ytrain_categorical, random_state=42
)
y_val1 = y_val[:, 1]

# 2. Cargar modelo pre-entrenado
model = get_model(width=128, height=128, depth=64)
model.load_weights("models/3d_image_classification.h5")

# 3. Predicción Vectorizada
print("Generando predicciones...")
val_predict = model.predict(X_val, verbose=1, batch_size=2)
val_label_predict = val_predict[:, 1]
y_pred = (val_label_predict > 0.5).astype(int)

# 4. Métricas
roc_auc = roc_auc_score(y_val1, val_label_predict)
val_acc = accuracy_score(y_val1, y_pred)
cf_matrix = confusion_matrix(y_val1, y_pred)

# Extraer True Positives, False Positives, etc. de la matriz
tn, fp, fn, tp = cf_matrix.ravel()

recall = tp / (tp + fn) if (tp + fn) > 0 else 0
especificidad = tn / (tn + fp) if (tn + fp) > 0 else 0
f1_score = 2 * ((val_acc * recall) / (val_acc + recall)) if (val_acc + recall) > 0 else 0

print("--- RESULTADOS ---")
print(f"AUROC: {roc_auc:.4f}")
print(f"Accuracy: {val_acc:.4f}")
print(f"Recall (Sensibilidad): {recall:.4f}")
print(f"Especificidad: {especificidad:.4f}")
print(f"F1-score: {f1_score:.4f}")

# 5. Gráficas
plt.figure(figsize=(12, 5))

# Curva ROC
plt.subplot(1, 2, 1)
fpr, tpr, thresholds = roc_curve(y_val1, val_label_predict)
plt.plot(fpr, tpr, color="red", lw=2, label=f"ROC curve (AUC = {roc_auc:.2f})")
plt.plot([0, 1], [0, 1], color="navy", lw=2, linestyle="--")
plt.xlabel("Tasa de Falsos Positivos")
plt.ylabel("Tasa de Verdaderos Positivos")
plt.title("Curva ROC")
plt.legend(loc="lower right")

# Matriz de Confusión
plt.subplot(1, 2, 2)
sns.heatmap(cf_matrix, annot=True, cmap='Blues', fmt='g',
            xticklabels=['Negativo','Positivo'], yticklabels=['Negativo','Positivo'])
plt.title('Matriz de Confusión')
plt.xlabel('Valores Predichos')
plt.ylabel('Valores Reales')

plt.tight_layout()
plt.savefig('metricas_evaluacion.png')
print("Gráficas guardadas como 'metricas_evaluacion.png'")