# -*- coding: utf-8 -*-
"""model_3d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TwjEiDV5f3Xgs2km9NdYuDL5RyyEdAMW
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

def get_model(width=128, height=128, depth=64):
    """
    Construye una arquitectura CNN 3D con conexiones residuales para la
    clasificación volumétrica de resonancias magnéticas (Glioblastoma).
    """
    inputs = keras.Input((width, height, depth, 1))

    # Bloque Inicial
    x = layers.Conv3D(filters=32, kernel_size=6, padding='same', use_bias=False, activation="relu")(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPool3D(pool_size=2, strides=2, padding='same')(x)

    # Bloque Residual 1
    x1 = layers.Conv3D(filters=32, kernel_size=3, strides=1, padding='same', use_bias=False, activation="relu")(x)
    x1 = layers.BatchNormalization()(x1)
    x1 = layers.ReLU()(x1)
    x1 = layers.Conv3D(filters=32, kernel_size=3, strides=1, padding='same', use_bias=False, activation="relu")(x1)
    x1 = layers.BatchNormalization()(x1)
    x = x + x1
    x = layers.Dropout(0.25)(x)
    x = layers.Conv3D(filters=32, kernel_size=3, strides=1, padding='same', use_bias=False, activation="relu")(x)

    # Bloque Residual 2
    x1 = layers.Conv3D(filters=64, kernel_size=3, strides=2, padding='same', use_bias=False, activation="relu")(x)
    x1 = layers.BatchNormalization()(x1)
    x1 = layers.ReLU()(x1)
    x1 = layers.Conv3D(filters=64, kernel_size=3, strides=1, padding='same', use_bias=False, activation="relu")(x1)
    x1 = layers.BatchNormalization()(x1)
    x = layers.Conv3D(filters=64, kernel_size=1, strides=2, use_bias=False, activation="relu")(x)
    x = layers.BatchNormalization()(x)
    x = x + x1
    x = layers.Dropout(0.25)(x)
    x = layers.Conv3D(filters=64, kernel_size=3, strides=1, padding='same', use_bias=False, activation="relu")(x)

    # Bloque Residual 3
    x1 = layers.Conv3D(filters=128, kernel_size=3, strides=2, padding='same', use_bias=False, activation="relu")(x)
    x1 = layers.BatchNormalization()(x1)
    x1 = layers.ReLU()(x1)
    x1 = layers.Conv3D(filters=128, kernel_size=3, strides=1, padding='same', use_bias=False, activation="relu")(x1)
    x1 = layers.BatchNormalization()(x1)
    x = layers.Conv3D(filters=128, kernel_size=1, strides=2, use_bias=False, activation="relu")(x)
    x = layers.BatchNormalization()(x)
    x = x + x1
    x = layers.Dropout(0.25)(x)
    x = layers.Conv3D(filters=128, kernel_size=3, strides=1, padding='same', use_bias=False, activation="relu")(x)

    # Bloque Residual 4
    x1 = layers.Conv3D(filters=192, kernel_size=3, strides=2, padding='same', use_bias=False, activation="relu")(x)
    x1 = layers.BatchNormalization()(x1)
    x1 = layers.ReLU()(x1)
    x1 = layers.Conv3D(filters=192, kernel_size=2, strides=1, padding='same', use_bias=False, activation="relu")(x1)
    x1 = layers.BatchNormalization()(x1)
    x = layers.Conv3D(filters=192, kernel_size=1, strides=2, use_bias=False, activation="relu")(x)
    x = layers.BatchNormalization()(x)
    x = x + x1

    x = layers.Conv3D(filters=192, kernel_size=3, strides=1, padding='same', use_bias=False, activation="relu")(x)
    x = layers.Dropout(0.5)(x)

    # Flatten y Clasificación
    x = layers.GlobalAveragePooling3D()(x)
    x = layers.Dense(units=256, activation="relu")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.5)(x)
    x = layers.Dense(units=128, activation="relu")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.5)(x)
    x = layers.Dense(units=64, activation="relu")(x)

    outputs = layers.Dense(units=2, activation="softmax")(x)

    model = keras.Model(inputs, outputs, name="3dcnn_resnet")
    return model