# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Nszqy_Lstp0mHQ49Y8d2yXO0OBfKz2v
"""

import os
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import optimizers
from tensorflow.keras.utils import to_categorical

# Importamos la arquitectura desde nuestro otro archivo
from model_3d import get_model

# 1. Cargar Datos
print("Cargando datos...")
data_y = np.load('data/data_ytrain.npy')
data_x = np.load('data/data_xtrain.npy')

ytrain_categorical = to_categorical(data_y[:, 0], num_classes=2)

X_train, X_val, y_train, y_val = train_test_split(
    data_x, ytrain_categorical, test_size=0.2, stratify=ytrain_categorical, random_state=42
)

# 2. Instanciar y Compilar Modelo
model = get_model(width=128, height=128, depth=64)
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["acc"])

# 3. Callbacks (Guardado local, no en Drive)
os.makedirs("models", exist_ok=True)
checkpoint_path = "models/3d_image_classification.h5"

checkpoint_cb = keras.callbacks.ModelCheckpoint(
    checkpoint_path, save_best_only=True, monitor='val_acc', mode='max', verbose=1
)
early_stopping_cb = keras.callbacks.EarlyStopping(monitor="val_acc", patience=300)

# 4. Entrenamiento
batch_size = 4
epochs = 600

print(f"Iniciando entrenamiento: Batch={batch_size}, Epochs={epochs}")
model.fit(
    X_train, y_train, epochs=epochs, batch_size=batch_size,
    validation_data=(X_val, y_val), callbacks=[checkpoint_cb, early_stopping_cb], verbose=1
)